server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/zsgcdemo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
     #serverTimezone=GMT%2B8 设置时区
     #useUnicode=true&characterEncoding=UTF-8 解决HTML插入数据库时显示？？？
    driver-class-name: com.mysql.cj.jdbc.Driver
    #禁用所有静态资源规则 true：能访问
    #resources:
    #add-mappings: false

    #激活rest功能，
  mvc:
    hiddenmethod:
      filter:
        enabled: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-handlers-package: com.hzs.boot.user.entity
